<template>
    <section>
      <navheader></navheader>
      <category></category>
      <vitrina></vitrina>
      <topproduct></topproduct>
      <ourgallery></ourgallery>
      <channel></channel>
    </section>
</template>
